In [1]:
python.version

NameError: name 'python' is not defined

In [1]:
list1=[1,2,3]
print(type(list1))

<class 'list'>


In [3]:
import numpy as np

In [4]:
array1=np.array(list1)

In [5]:
print(type(array1))

<class 'numpy.ndarray'>


In [6]:
print(array1,array1.dtype)

[1 2 3] int32


In [7]:
array_int=np.array([1,2,3])

In [10]:
array_float=array_int.astype('float64')

In [14]:
print(array_float,type(array_float))

[1. 2. 3.] <class 'numpy.ndarray'>


In [18]:
np.arange(10).dtype

dtype('int32')

In [20]:
zero_array=np.zeros((3,2),dtype='int32')

In [21]:
print(zero_array)

[[0 0]
 [0 0]
 [0 0]]


In [23]:
zero_array.shape

(3, 2)

In [25]:
one_array=np.ones((3,2))
print(one_array)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [31]:
array1=np.arange(10)
print('array1:\n',array1)
array2=array1.reshape(2,5)
print('array2:\n',array2)
array3=array1.reshape(5,2)
print('array3:\n',array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [39]:
array1=np.arange(10)
array2=array1.reshape(-1,2)
print(array2.shape)
array3=array1.reshape(2,-1)
print(array3.shape)

(5, 2)
(2, 5)


In [41]:
array1=np.arange(8)
array3d=array1.reshape(2,2,2)
print('array3d:\n',array3d.tolist())

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]


In [48]:
array5=array3d.reshape(-1,1)
print('array5:\n',array5.tolist())
array5.shape

array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]


(8, 1)

In [436]:
array6=array1.reshape(-1,1)
print(array6.shape,array6.shape[0])

(3, 1) 3


In [59]:
array1=np.arange(start=1,stop=10)
print('array1:',array1)
value=array1[2]
print('vlaue:',value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
vlaue: 3
<class 'numpy.int32'>


In [438]:
array1=np.arange(1,10)
array2d=array1.reshape(3,3)
array2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
array1[0:3]

array([1, 2, 3])

In [66]:
array2d[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [68]:
array2d[0:2,1:]

array([[2, 3],
       [5, 6]])

In [69]:
array2d[[0,1],2]

array([3, 6])

In [70]:
array1[array1>5]

array([6, 7, 8, 9])

In [71]:
array1>5

array([False, False, False, False, False,  True,  True,  True,  True])

In [73]:
org_array=np.array([3,1,9,5])
print(np.sort(org_array),org_array)

[1 3 5 9] [3 1 9 5]


In [76]:
print(org_array.sort(),org_array)

None [1 3 5 9]


In [77]:
np.sort(org_array)[::-1]

array([9, 5, 3, 1])

In [78]:
np.sort(org_array)

array([1, 3, 5, 9])

In [79]:
array2d=np.array([[8,12],
                 [7,1 ]])
array2d

array([[ 8, 12],
       [ 7,  1]])

In [80]:
np.sort(array2d,axis=0)

array([[ 7,  1],
       [ 8, 12]])

In [83]:
np.sort(array2d,axis=1)

array([[ 8, 12],
       [ 1,  7]])

In [87]:
org_array=np.array([3,1,9,5])
np.argsort(org_array)[::-1]

array([2, 3, 0, 1], dtype=int64)

In [88]:
name_array=['John','Mike','Sarah','Kate','Samuel']
score_array=[78,95,84,98,88]

In [102]:
np.argsort(score_array)


array([0, 2, 4, 1, 3], dtype=int64)

In [99]:
name=np.array(name_array)#list로 변환
name[array]

array(['John', 'Sarah', 'Samuel', 'Mike', 'Kate'], dtype='<U6')

In [103]:
simport pandas as pd

In [108]:
titanic_df=pd.read_csv(r'C:\Users\PC\Desktop\새 폴더\train.csv')
type(titanic_df)

pandas.core.frame.DataFrame

In [109]:
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [111]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [112]:
titanic_df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [116]:
value_counts=titanic_df['Pclass'].value_counts()

In [117]:
value_counts

3    491
1    216
2    184
Name: Pclass, dtype: int64

In [118]:
titanic_pclass=titanic_df['Pclass']
print(type(titanic_pclass))

<class 'pandas.core.series.Series'>


In [119]:
titanic_pclass.head()

0    3
1    1
2    3
3    1
4    3
Name: Pclass, dtype: int64

In [120]:
col_name=['col1']
list1=[1,2,3]
array1=np.array(list1)
print('array1 shape:',array1.shape)

array1 shape: (3,)


In [122]:
#list->dataFrame
pd.DataFrame(list1,columns=col_name)

col1
0     1
1     2
2     3

In [123]:
#ndarray->dataFrame
pd.DataFrame(array1,columns=col_name)

col1
0     1
1     2
2     3

In [125]:
col_name2=['col1','col2','col3']
list2=[[1,2,3],[11,12,13]]
array2=np.array(list2)
array2.shape

(2, 3)

In [130]:
#list->dataframe
pd.DataFrame(list2,columns=col_name2)

col1  col2  col3
0     1     2     3
1    11    12    13

In [132]:
#ndarry->dataframe
pd.DataFrame(array2,columns=col_name2)

col1  col2  col3
0     1     2     3
1    11    12    13

In [136]:
dict={'col1':[1,11],'col2':[2,22],'col3':[3,33]}
df_dict=pd.DataFrame(dict)

In [141]:
type(df_dict.values)

numpy.ndarray

In [144]:
#dataframe->list
list3=df_dict.values.tolist()
type(list3)

list

In [145]:
#dataframe->dict
df_dict.to_dict('list')

{'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}

In [146]:
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [170]:
titanic_df['Age_0']=0
titanic_df.head(3)

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked  Age_0
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S      0
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C      0
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S      0

In [171]:
titanic_df['Age_by_10']=titanic_df['Age']*10
titanic_df['Family_No']=titanic_df['SibSp']+titanic_df['Parch']+1
titanic_df.head(3)

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked  Age_0  Age_by_10  Family_No
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S      0      220.0          2
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C      0      380.0          2
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S      0      260.0          1

In [154]:
titanic_drop=titanic_df.drop('Age_0',axis=1)

In [166]:
titanic_df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  Age_by_10  Family_No  \
0        0         A/5 21171   7.2500   NaN        S      220.0          2   
1        0          PC 17599  71.2833   C85        C      380.0          2   
2        0  STON/O2. 3101282   7.9250   NaN        S      260.0          1   
3        0            113803  53.1000  C123        S      350.0          2   
4        0            373450   8.0500   NaN        S      350.0          1   
..     ...               ...      ...   ...      ...        ...        ...   
886      0            211536  13.0000   NaN        S      270.0          1   
887      0            112053  30.0000   B42        S      190.0          1   
888      2        W./C. 6607  23.4500   NaN        S        NaN          4   
889      0            111369  30.0000  C148        C      260.0          1   
890      0            370376   7.7500   NaN        Q      320.0          1   

     Age_0  
0        0  
1        0  
2        0  
3        0  
4        0  
..     ...  
886      0  
887      0  
888      0  
889      0  
890      0  

[891 rows x 15 columns]

In [172]:
titanic_df.drop(['Age_0','Age_by_10','Family_No'],axis=1,inplace=True)
titanic_df.head(3)

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S

In [175]:
pd.set_option('display.width',1000)
pd.set_option('display.max_colwidth',15)
print(titanic_df.head(3))

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
3            4         1       1  Futrelle, M...  female  35.0      1      0  113803  53.1000  C123        S
4            5         0       3  Allen, Mr. ...    male  35.0      0      0  373450   8.0500   NaN        S
5            6         0       3  Moran, Mr. ...    male   NaN      0      0  330877   8.4583   NaN        Q


In [176]:
titanic_df.drop([0,1,2],axis=0,inplace=True)
print(titanic_df.head(3))

KeyError: '[0 1 2] not found in axis'

In [177]:
titanic_df=pd.read_csv(r'C:\Users\PC\Desktop\새 폴더\train.csv')

In [183]:
indexes=titanic_df.index

In [184]:
indexes[:5].values

array([0, 1, 2, 3, 4], dtype=int64)

In [186]:
titanic_df['Fare'].sum()

28693.9493

In [187]:
titanic_df.reset_index(inplace=False)

index  PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0        0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1        1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2        2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S
3        3            4         1       1  Futrelle, M...  female  35.0      1      0          113803  53.1000  C123        S
4        4            5         0       3  Allen, Mr. ...    male  35.0      0      0          373450   8.0500   NaN        S
..     ...          ...       ...     ...             ...     ...   ...    ...    ...             ...      ...   ...      ...
886    886          887         0       2  Montvila, R...    male  27.0      0      0          211536  13.0000   NaN        S
887    887          888         1       1  Graham, Mis...  female  19.0      0      0          112053  30.0000   B42        S
888    888          889         0       3  Johnston, M...  female   NaN      1      2      W./C. 6607  23.4500   NaN        S
889    889          890         1       1  Behr, Mr. K...    male  26.0      0      0          111369  30.0000  C148        C
890    890          891         0       3  Dooley, Mr....    male  32.0      0      0          370376   7.7500   NaN        Q

[891 rows x 13 columns]

In [191]:
value_counts=titanic_df['Pclass'].value_counts()
print(value_counts)
print(type(value_counts))

3    491
1    216
2    184
Name: Pclass, dtype: int64
<class 'pandas.core.series.Series'>


In [194]:
new_value_counts=value_counts.reset_index(inplace=False,drop=True)
print(new_value_counts)
print(type(new_value_counts))

0    491
1    216
2    184
Name: Pclass, dtype: int64
<class 'pandas.core.series.Series'>


In [195]:
titanic_df[titanic_df['Pclass']==3].head(3)

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket   Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171  7.250   NaN        S
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...  7.925   NaN        S
4            5         0       3  Allen, Mr. ...    male  35.0      0      0          373450  8.050   NaN        S

In [196]:
titanic_df[0:2]

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch     Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0  A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0   PC 17599  71.2833   C85        C

In [200]:
data={'Name':['Chulmin','Eunkyung','Jinwoong','Soobeom'],
     'Year':[2011,2016,2015,2015],
     'Gender':['Male','Female','Male','Male']}
data_df=pd.DataFrame(data,index=['one','two','three','four'])
data_df

Name  Year  Gender
one     Chulmin  2011    Male
two    Eunkyung  2016  Female
three  Jinwoong  2015    Male
four    Soobeom  2015    Male

In [206]:
data_df_reset=data_df.reset_index()
data_df_reset=data_df_reset.rename(columns={'index':'old_index'})
data_df_reset.index=data_df_reset.index+1
data_df_reset

old_index      Name  Year  Gender
1       one   Chulmin  2011    Male
2       two  Eunkyung  2016  Female
3     three  Jinwoong  2015    Male
4      four   Soobeom  2015    Male

In [210]:
print(data_df.iloc[0,0])
print(data_df_reset.iloc[0,1])
print(data_df.loc['one','Name'])
print(data_df_reset.loc[1,'Name'])

Chulmin
Chulmin
Chulmin
Chulmin


In [225]:
titanic_df[titanic_df['Age']>60][['Name','Age']].head(3)

Name   Age
33  Wheadon, Mr...  66.0
54  Ostby, Mr. ...  65.0
96  Goldschmidt...  71.0

In [226]:
titanic_df.loc[titanic_df['Age']>60,['Name','Age']].head(3)

Name   Age
33  Wheadon, Mr...  66.0
54  Ostby, Mr. ...  65.0
96  Goldschmidt...  71.0

In [231]:
titanic_df[(titanic_df['Age']>60)&(titanic_df['Pclass']==1)&(titanic_df['Sex']=='female')]

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
275          276         1       1  Andrews, Mi...  female  63.0      1      0   13502  77.9583    D7        S
829          830         1       1  Stone, Mrs....  female  62.0      0      0  113572  80.0000   B28      NaN

In [232]:
titanic_df.sort_values(by=['Name'])

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch         Ticket     Fare Cabin Embarked
845          846         0       3  Abbing, Mr....    male  42.0      0      0      C.A. 5547   7.5500   NaN        S
746          747         0       3  Abbott, Mr....    male  16.0      1      1      C.A. 2673  20.2500   NaN        S
279          280         1       3  Abbott, Mrs...  female  35.0      1      1      C.A. 2673  20.2500   NaN        S
308          309         0       2  Abelson, Mr...    male  30.0      1      0      P/PP 3381  24.0000   NaN        C
874          875         1       2  Abelson, Mr...  female  28.0      1      0      P/PP 3381  24.0000   NaN        C
..           ...       ...     ...             ...     ...   ...    ...    ...            ...      ...   ...      ...
286          287         1       3  de Mulder, ...    male  30.0      0      0         345774   9.5000   NaN        S
282          283         0       3  de Pelsmaek...    male  16.0      0      0         345778   9.5000   NaN        S
361          362         0       2  del Carlo, ...    male  29.0      1      0  SC/PARIS 2167  27.7208   NaN        C
153          154         0       3  van Billiar...    male  40.5      0      2       A/5. 851  14.5000   NaN        S
868          869         0       3  van Melkebe...    male   NaN      0      0         345777   9.5000   NaN        S

[891 rows x 12 columns]

In [233]:
titanic_df.sort_values(by=['Pclass','Name'],ascending=True)

PassengerId  Survived  Pclass            Name     Sex    Age  SibSp  Parch    Ticket      Fare    Cabin Embarked
730          731         1       1  Allen, Miss...  female  29.00      0      0     24160  211.3375       B5        S
305          306         1       1  Allison, Ma...    male   0.92      1      2    113781  151.5500  C22 C26        S
297          298         0       1  Allison, Mi...  female   2.00      1      2    113781  151.5500  C22 C26        S
498          499         0       1  Allison, Mr...  female  25.00      1      2    113781  151.5500  C22 C26        S
460          461         1       1  Anderson, M...    male  48.00      0      0     19952   26.5500      E12        S
..           ...       ...     ...             ...     ...    ...    ...    ...       ...       ...      ...      ...
559          560         1       3  de Messemae...  female  36.00      1      0    345572   17.4000      NaN        S
286          287         1       3  de Mulder, ...    male  30.00      0      0    345774    9.5000      NaN        S
282          283         0       3  de Pelsmaek...    male  16.00      0      0    345778    9.5000      NaN        S
153          154         0       3  van Billiar...    male  40.50      0      2  A/5. 851   14.5000      NaN        S
868          869         0       3  van Melkebe...    male    NaN      0      0    345777    9.5000      NaN        S

[891 rows x 12 columns]

In [234]:
titanic_df.mean()

PassengerId    446.000000
Survived         0.383838
Pclass           2.308642
Age             29.699118
SibSp            0.523008
Parch            0.381594
Fare            32.204208
dtype: float64

In [235]:
titanic_df.groupby('Pclass').count()

PassengerId  Survived  Name  Sex  Age  SibSp  Parch  Ticket  Fare  Cabin  Embarked
Pclass                                                                                    
1               216       216   216  216  186    216    216     216   216    176       214
2               184       184   184  184  173    184    184     184   184     16       184
3               491       491   491  491  355    491    491     491   491     12       491

In [237]:
titanic_df.groupby('Pclass')[['PassengerId','Survived']].count()

PassengerId  Survived
Pclass                       
1               216       216
2               184       184
3               491       491

In [238]:
titanic_df.groupby('Pclass')['Age'].agg([max,min])

max   min
Pclass            
1       80.0  0.92
2       70.0  0.67
3       74.0  0.42

In [240]:
agg_format={'Age':'max','SibSp':'sum','Fare':'mean'}
titanic_df.groupby('Pclass').agg(agg_format)

Age  SibSp       Fare
Pclass                        
1       80.0     90  84.154687
2       70.0     74  20.662183
3       74.0    302  13.675550

In [241]:
titanic_df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [243]:
titanic_df['Cabin'].head(3)

0    NaN
1    C85
2    NaN
Name: Cabin, dtype: object

In [245]:
titanic_df['Cabin']=titanic_df['Cabin'].fillna('C000')
titanic_df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin            0
Embarked         2
dtype: int64

In [250]:
titanic_df['Age']=titanic_df['Age'].fillna(titanic_df['Age'].mean())
titanic_df['Embarked']=titanic_df['Embarked'].fillna('S')
titanic_df.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [251]:
def get_square(a):
    return a**2
print(get_square(3))

9


In [254]:
lambda_square=lambda x : x**2
print(lambda_square(3))

9


In [256]:
a=[1,2,3]
squares=map(lambda x : x**2,a)
list(squares)

[1, 4, 9]

In [257]:
titanic_df['Name_len']=titanic_df['Name'].apply(lambda x : len(x))
titanic_df[['Name','Name_len']]

Name  Name_len
0    Braund, Mr....        23
1    Cumings, Mr...        51
2    Heikkinen, ...        22
3    Futrelle, M...        44
4    Allen, Mr. ...        24
..              ...       ...
886  Montvila, R...        21
887  Graham, Mis...        28
888  Johnston, M...        40
889  Behr, Mr. K...        21
890  Dooley, Mr....        19

[891 rows x 2 columns]

In [259]:
titanic_df['Child_Adult']=titanic_df['Age'].apply(lambda x : 'Child' if x<15 else 'Adult')
titanic_df[['Age','Child_Adult']].head(8)

Age Child_Adult
0  22.000000       Adult
1  38.000000       Adult
2  26.000000       Adult
3  35.000000       Adult
4  35.000000       Adult
5  29.699118       Adult
6  54.000000       Adult
7   2.000000       Child

In [263]:
titanic_df['Age_Cat']=titanic_df['Age'].apply(lambda x : 'Child' if x<=15 else ('Adult' if x<=60 else 'Elderly'))
titanic_df['Age_Cat'].value_counts()

Adult      786
Child       83
Elderly     22
Name: Age_Cat, dtype: int64

In [265]:
def get_category(age):
    cat=''
    if age<=5 : cat='Baby'
    elif age<=12 : cat='Child'
    elif age<=18 : cat='Teenage'
    elif age<=25 : cat='Student'
    elif age<=35 : cat='Young Adult'
    elif age<=60 : cat='Adult'
    else : cat='Elderly'
        
    return cat

titanic_df['Age_cat']=titanic_df['Age'].apply(lambda x : get_category(x))
titanic_df[['Age','Age_cat']]

Age      Age_cat
0    22.000000      Student
1    38.000000        Adult
2    26.000000  Young Adult
3    35.000000  Young Adult
4    35.000000  Young Adult
..         ...          ...
886  27.000000  Young Adult
887  19.000000      Student
888  29.699118  Young Adult
889  26.000000  Young Adult
890  32.000000  Young Adult

[891 rows x 2 columns]

In [270]:
array1=np.array([1,2,3])
print(type(array1))
print(array1.shape)

<class 'numpy.ndarray'>
(3,)


In [273]:
array2=np.array([[1,2,3],
                [2,3,4]])
print(type(array2))
print(array2.shape)

<class 'numpy.ndarray'>
(2, 3)


In [275]:
array3=np.array([[1,2,3]])
print(type(array3))
print(array3.shape)

<class 'numpy.ndarray'>
(1, 3)


In [276]:
list2=[1,2,'test']
array2=np.array(list2)
print(array2.dtype)

<U11


In [278]:
list3=[1,2,3.0]
array3=np.array(list3)
print(array3.dtype)

float64


In [279]:
array3.astype('int32')

array([1, 2, 3])

In [282]:
array1=np.arange(10)
print(array1.reshape(2,5))
print(array1.reshape(-1,5))

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [283]:
array4=np.arange(1024)
array4.reshape(-1,8)

array([[   0,    1,    2, ...,    5,    6,    7],
       [   8,    9,   10, ...,   13,   14,   15],
       [  16,   17,   18, ...,   21,   22,   23],
       ...,
       [1000, 1001, 1002, ..., 1005, 1006, 1007],
       [1008, 1009, 1010, ..., 1013, 1014, 1015],
       [1016, 1017, 1018, ..., 1021, 1022, 1023]])

In [285]:
type(array1)

numpy.ndarray

In [287]:
array2=array1.tolist()
type(array2)

list

In [291]:
np.arange(1,10,step=2)

array([1, 3, 5, 7, 9])

In [292]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        891 non-null    object 
 11  Embarked     891 non-null    object 
 12  Name_len     891 non-null    int64  
 13  Child_Adult  891 non-null    object 
 14  Age_Cat      891 non-null    object 
 15  Age_cat      891 non-null    object 
dtypes: float64(2), int64(6), object(8)
memory usage: 111.5+ KB


In [297]:
array1==np.arange(10)
print(array1)
print(array1[-1])

[0 1 2 3 4 5 6 7 8 9]
9


In [298]:
array1[-1]=0

In [299]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 0])

In [306]:
array1=np.arange(1,10)
array2d=array1.reshape(3,3)
print(array2d[0:2,1:3])

[[2 3]
 [5 6]]


In [307]:
array2d[[0,1],2]

array([3, 6])

In [308]:
array2d[array2d>5]

array([6, 7, 8, 9])

In [317]:
org_array=np.array([3,1,9,5])

In [313]:
np.sort(org_array)[::-1]

array([9, 5, 3, 1])

In [312]:
org_array.sort()
print(org_array)

[1 3 5 9]


In [316]:
np.sort(array2d,axis=1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [318]:
np.argsort(org_array)

array([1, 0, 3, 2], dtype=int64)

In [336]:
name_array=['Jhon','Mike','Sarah','Kate','Samuel']
name=np.array(name_array)
score_array=[78,95,84,98,88]
score_num=np.array(score_array)
score=np.argsort(score_num)
score

array([0, 2, 4, 1, 3], dtype=int64)

In [332]:
name[score]

array(['Jhon', 'Sarah', 'Samuel', 'Mike', 'Kate'], dtype='<U6')

In [341]:
A=np.array([[1,2],
         [3,4]])
B=np.array([[5,6],
           [7,8]])

In [339]:
np.transpose(A)

array([[1, 3],
       [2, 4]])

In [342]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [346]:
titanic_df=pd.read_csv(r'C:\Users\PC\Desktop\새 폴더\train.csv')
titanic_df.shape

(891, 12)

In [347]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [349]:
titanic_df.groupby('Pclass').count()

PassengerId  Survived  Name  Sex  Age  SibSp  Parch  Ticket  Fare  Cabin  Embarked
Pclass                                                                                    
1               216       216   216  216  186    216    216     216   216    176       214
2               184       184   184  184  173    184    184     184   184     16       184
3               491       491   491  491  355    491    491     491   491     12       491

In [353]:
titanic_df.groupby('Pclass')['Age'].agg([min,max])

min   max
Pclass            
1       0.92  80.0
2       0.67  70.0
3       0.42  74.0

In [355]:
titanic_df.describe()

PassengerId    Survived      Pclass         Age       SibSp       Parch        Fare
count   891.000000  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean    446.000000    0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std     257.353842    0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min       1.000000    0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%     223.500000    0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%     446.000000    0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%     668.500000    1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max     891.000000    1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [357]:
#데이터분포확인
value_counts=titanic_df['Pclass'].value_counts()
value_counts

3    491
1    216
2    184
Name: Pclass, dtype: int64

In [360]:
value_counts.reset_index()

index  Pclass
0      3     491
1      1     216
2      2     184

In [364]:
titanic_df['Pclass']

0      3
1      1
2      3
3      1
4      3
      ..
886    2
887    1
888    3
889    1
890    3
Name: Pclass, Length: 891, dtype: int64

In [367]:
col_name1=['col1']
list1=[1,2,3]
pd.DataFrame(list1,columns=col_name1)

col1
0     1
1     2
2     3

In [369]:
array1=np.array(list1)
pd.DataFrame(array1,columns=col_name1)

col1
0     1
1     2
2     3

In [373]:
dict={'col1':[1,11],'col2':[2,22],'col3':[3,33]}
df_dict=pd.DataFrame(dict)
df_dict.values

array([[ 1,  2,  3],
       [11, 22, 33]], dtype=int64)

In [374]:
titanic_df['Age_0']=0
titanic_df.head(3)

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked  Age_0
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S      0
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C      0
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S      0

In [380]:
titanic_df.drop('Age_0',axis=1)

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0              1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1              2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2              3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S
3              4         1       1  Futrelle, M...  female  35.0      1      0          113803  53.1000  C123        S
4              5         0       3  Allen, Mr. ...    male  35.0      0      0          373450   8.0500   NaN        S
..           ...       ...     ...             ...     ...   ...    ...    ...             ...      ...   ...      ...
886          887         0       2  Montvila, R...    male  27.0      0      0          211536  13.0000   NaN        S
887          888         1       1  Graham, Mis...  female  19.0      0      0          112053  30.0000   B42        S
888          889         0       3  Johnston, M...  female   NaN      1      2      W./C. 6607  23.4500   NaN        S
889          890         1       1  Behr, Mr. K...    male  26.0      0      0          111369  30.0000  C148        C
890          891         0       3  Dooley, Mr....    male  32.0      0      0          370376   7.7500   NaN        Q

[891 rows x 12 columns]

In [382]:
titanic_df['Age_by_10']=titanic_df['Age']*10+100

In [387]:
titanic_df.drop(['Age_0','Age_by_10'],axis=1,inplace=True)

KeyError: "['Age_0' 'Age_by_10'] not found in axis"

In [393]:
index=titanic_df.index.values
index[:5]

array([0, 1, 2, 3, 4], dtype=int64)

In [396]:
titanic_reset=titanic_df.reset_index()

In [401]:
titanic_reset=titanic_reset.rename(columns={'index':'Index'})

In [398]:
titanic_df['AdultCild']=titanic_df['Age'].apply(lambda x : 'Child' if x<15 else 'Adult')

In [400]:
titanic_df

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked AdultCild
0              1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S     Adult
1              2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C     Adult
2              3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S     Adult
3              4         1       1  Futrelle, M...  female  35.0      1      0          113803  53.1000  C123        S     Adult
4              5         0       3  Allen, Mr. ...    male  35.0      0      0          373450   8.0500   NaN        S     Adult
..           ...       ...     ...             ...     ...   ...    ...    ...             ...      ...   ...      ...       ...
886          887         0       2  Montvila, R...    male  27.0      0      0          211536  13.0000   NaN        S     Adult
887          888         1       1  Graham, Mis...  female  19.0      0      0          112053  30.0000   B42        S     Adult
888          889         0       3  Johnston, M...  female   NaN      1      2      W./C. 6607  23.4500   NaN        S     Adult
889          890         1       1  Behr, Mr. K...    male  26.0      0      0          111369  30.0000  C148        C     Adult
890          891         0       3  Dooley, Mr....    male  32.0      0      0          370376   7.7500   NaN        Q     Adult

[891 rows x 13 columns]

In [408]:
titanic_reset.index=titanic_reset.index-3
titanic_reset

Index  PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
1        0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
2        1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
3        2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S
4        3            4         1       1  Futrelle, M...  female  35.0      1      0          113803  53.1000  C123        S
5        4            5         0       3  Allen, Mr. ...    male  35.0      0      0          373450   8.0500   NaN        S
..     ...          ...       ...     ...             ...     ...   ...    ...    ...             ...      ...   ...      ...
887    886          887         0       2  Montvila, R...    male  27.0      0      0          211536  13.0000   NaN        S
888    887          888         1       1  Graham, Mis...  female  19.0      0      0          112053  30.0000   B42        S
889    888          889         0       3  Johnston, M...  female   NaN      1      2      W./C. 6607  23.4500   NaN        S
890    889          890         1       1  Behr, Mr. K...    male  26.0      0      0          111369  30.0000  C148        C
891    890          891         0       3  Dooley, Mr....    male  32.0      0      0          370376   7.7500   NaN        Q

[891 rows x 13 columns]

In [409]:
titanic_reset.iloc[0,0]

0

In [414]:
titanic_reset.loc[1,'Index']

0

In [416]:
titanic_reset[titanic_reset['Age']>60]

Index  PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch       Ticket      Fare        Cabin Embarked
34      33           34         0       2  Wheadon, Mr...    male  66.0      0      0   C.A. 24579   10.5000          NaN        S
55      54           55         0       1  Ostby, Mr. ...    male  65.0      0      1       113509   61.9792          B30        C
97      96           97         0       1  Goldschmidt...    male  71.0      0      0     PC 17754   34.6542           A5        C
117    116          117         0       3  Connors, Mr...    male  70.5      0      0       370369    7.7500          NaN        Q
171    170          171         0       1  Van der hoe...    male  61.0      0      0       111240   33.5000          B19        S
253    252          253         0       1  Stead, Mr. ...    male  62.0      0      0       113514   26.5500          C87        S
276    275          276         1       1  Andrews, Mi...  female  63.0      1      0        13502   77.9583           D7        S
281    280          281         0       3  Duane, Mr. ...    male  65.0      0      0       336439    7.7500          NaN        Q
327    326          327         0       3  Nysveen, Mr...    male  61.0      0      0       345364    6.2375          NaN        S
439    438          439         0       1  Fortune, Mr...    male  64.0      1      4        19950  263.0000  C23 C25 C27        S
457    456          457         0       1  Millet, Mr....    male  65.0      0      0        13509   26.5500          E38        S
484    483          484         1       3  Turkula, Mr...  female  63.0      0      0         4134    9.5875          NaN        S
494    493          494         0       1  Artagaveyti...    male  71.0      0      0     PC 17609   49.5042          NaN        C
546    545          546         0       1  Nicholson, ...    male  64.0      0      0          693   26.0000          NaN        S
556    555          556         0       1  Wright, Mr....    male  62.0      0      0       113807   26.5500          NaN        S
571    570          571         1       2  Harris, Mr....    male  62.0      0      0  S.W./PP 752   10.5000          NaN        S
626    625          626         0       1  Sutton, Mr....    male  61.0      0      0        36963   32.3208          D50        S
631    630          631         1       1  Barkworth, ...    male  80.0      0      0        27042   30.0000          A23        S
673    672          673         0       2  Mitchell, M...    male  70.0      0      0   C.A. 24580   10.5000          NaN        S
746    745          746         0       1  Crosby, Cap...    male  70.0      1      1    WE/P 5735   71.0000          B22        S
830    829          830         1       1  Stone, Mrs....  female  62.0      0      0       113572   80.0000          B28      NaN
852    851          852         0       3  Svensson, M...    male  74.0      0      0       347060    7.7750          NaN        S

In [417]:
titanic_reset[titanic_reset['Age']>60][['Name','Age']]

Name   Age
34   Wheadon, Mr...  66.0
55   Ostby, Mr. ...  65.0
97   Goldschmidt...  71.0
117  Connors, Mr...  70.5
171  Van der hoe...  61.0
253  Stead, Mr. ...  62.0
276  Andrews, Mi...  63.0
281  Duane, Mr. ...  65.0
327  Nysveen, Mr...  61.0
439  Fortune, Mr...  64.0
457  Millet, Mr....  65.0
484  Turkula, Mr...  63.0
494  Artagaveyti...  71.0
546  Nicholson, ...  64.0
556  Wright, Mr....  62.0
571  Harris, Mr....  62.0
626  Sutton, Mr....  61.0
631  Barkworth, ...  80.0
673  Mitchell, M...  70.0
746  Crosby, Cap...  70.0
830  Stone, Mrs....  62.0
852  Svensson, M...  74.0

In [422]:
titanic_reset[(titanic_reset['Age']>60)&(titanic_reset['Sex']=='female')&(titanic_reset['Pclass']==1)]

Index  PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
276    275          276         1       1  Andrews, Mi...  female  63.0      1      0   13502  77.9583    D7        S
830    829          830         1       1  Stone, Mrs....  female  62.0      0      0  113572  80.0000   B28      NaN

In [424]:
titanic_df.sort_values(['Name'],ascending=False)

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch         Ticket     Fare Cabin Embarked AdultCild
868          869         0       3  van Melkebe...    male   NaN      0      0         345777   9.5000   NaN        S     Adult
153          154         0       3  van Billiar...    male  40.5      0      2       A/5. 851  14.5000   NaN        S     Adult
361          362         0       2  del Carlo, ...    male  29.0      1      0  SC/PARIS 2167  27.7208   NaN        C     Adult
282          283         0       3  de Pelsmaek...    male  16.0      0      0         345778   9.5000   NaN        S     Adult
286          287         1       3  de Mulder, ...    male  30.0      0      0         345774   9.5000   NaN        S     Adult
..           ...       ...     ...             ...     ...   ...    ...    ...            ...      ...   ...      ...       ...
874          875         1       2  Abelson, Mr...  female  28.0      1      0      P/PP 3381  24.0000   NaN        C     Adult
308          309         0       2  Abelson, Mr...    male  30.0      1      0      P/PP 3381  24.0000   NaN        C     Adult
279          280         1       3  Abbott, Mrs...  female  35.0      1      1      C.A. 2673  20.2500   NaN        S     Adult
746          747         0       3  Abbott, Mr....    male  16.0      1      1      C.A. 2673  20.2500   NaN        S     Adult
845          846         0       3  Abbing, Mr....    male  42.0      0      0      C.A. 5547   7.5500   NaN        S     Adult

[891 rows x 13 columns]

In [425]:
titanic_df.sort_values(['Age','Name'])

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked AdultCild
803          804         1       3  Thomas, Mas...    male  0.42      0      1    2625   8.5167   NaN        C     Child
755          756         1       2  Hamalainen,...    male  0.67      1      1  250649  14.5000   NaN        S     Child
644          645         1       3  Baclini, Mi...  female  0.75      2      1    2666  19.2583   NaN        C     Child
469          470         1       3  Baclini, Mi...  female  0.75      2      1    2666  19.2583   NaN        C     Child
78            79         1       2  Caldwell, M...    male  0.83      0      2  248738  29.0000   NaN        S     Child
..           ...       ...     ...             ...     ...   ...    ...    ...     ...      ...   ...      ...       ...
55            56         1       1  Woolner, Mr...    male   NaN      0      0   19947  35.5000   C52        S     Adult
354          355         0       3  Yousif, Mr....    male   NaN      0      0    2647   7.2250   NaN        C     Adult
495          496         0       3  Yousseff, M...    male   NaN      0      0    2627  14.4583   NaN        C     Adult
240          241         0       3  Zabour, Mis...  female   NaN      1      0    2665  14.4542   NaN        C     Adult
868          869         0       3  van Melkebe...    male   NaN      0      0  345777   9.5000   NaN        S     Adult

[891 rows x 13 columns]

In [426]:
titanic_df.count()

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
AdultCild      891
dtype: int64

In [430]:
titanic_df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
AdultCild        0
dtype: int64

In [431]:
agg_format={'Age':'max','SibSp':'sum','Fare':'mean'}
titanic_df.groupby('Pclass').agg(agg_format)

Age  SibSp       Fare
Pclass                        
1       80.0     90  84.154687
2       70.0     74  20.662183
3       74.0    302  13.675550

In [432]:
titanic_df.groupby('Pclass').agg(['max','min'])

PassengerId     Survived                Name                   Sex           Age       SibSp     Parch          Ticket              Fare      AdultCild       
               max min      max min             max             min   max     min   max   min   max min   max min         max     min       max  min       max    min
Pclass                                                                                                                                                               
1              890   2        1   0  Young, Miss...  Allen, Miss...  male  female  80.0  0.92     3   0     4   0   WE/P 5735  110152  512.3292  0.0     Child  Adult
2              887  10        1   0  del Carlo, ...  Abelson, Mr...  male  female  70.0  0.67     3   0     3   0   W/C 14208   11668   73.5000  0.0     Child  Adult
3              891   1        1   0  van Melkebe...  Abbing, Mr....  male  female  74.0  0.42     8   0     6   0  W./C. 6609   12460   69.5500  0.0     Child  Adult