In [1]:
conda install scikit-learn

Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\PC\anaconda3

  added / updated specs:
    - scikit-learn


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2020.12.8  |       haa95532_0         122 KB
    certifi-2020.12.5          |   py38haa95532_0         141 KB
    openssl-1.1.1i             |       h2bbff1b_0         4.8 MB
    scikit-learn-0.23.2        |   py38h47e9c7a_0         4.7 MB
    ------------------------------------------------------------
                                           Total:         9.8 MB

The following packages will be UPDATED:

  ca-certificates                              2020.10.14-0 --> 2020.12.8-haa95532_0
  certifi            pkgs/main/noarch::certifi-2020.6.20-p~ --> pkgs/main/win-64::certifi-2020.12.5-py38haa95532_0
  openssl                                 1.1.1h-he774522_0 --> 1.1.1i

In [2]:
pip install  scikit-learn

Note: you may need to restart the kernel to use updated packages.


In [4]:
import sklearn
print(sklearn.__version__)

0.23.2


In [7]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [8]:
import pandas as pd
import numpy as np

In [11]:
iris=load_iris()
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [65]:
iris_df=pd.DataFrame(iris.data,columns=iris.feature_names)
iris_df['label']=iris.target
iris_df.index

RangeIndex(start=0, stop=150, step=1)

In [19]:
#iris.target은 붓꽃 데이터 세트에서 레이블(결정값)데이터를 numpy로 가지고 있다.
print('iris target명 :' ,iris.target_names)
print('iris target값 :' ,iris.target)

iris target명 : ['setosa' 'versicolor' 'virginica']
iris target값 : [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [17]:
#iris는 데이터 세트에서 피처(feature)만으로 된 데이터 numpy를 갖고 있다.
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [23]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [27]:
#train test로 분리 (X: feature data set, y: label data set)
X_train,X_test,y_train,y_test=train_test_split(iris.data,iris.target,random_state=11,test_size=0.2)

In [29]:
#모델학습(모델: DecisinoTreeClassifier 이용)
dt_clf=DecisionTreeClassifier(random_state=11)
dt_clf.fit(X_train,y_train)

DecisionTreeClassifier(random_state=11)

In [33]:
#학습된 모델로 테스트데이터 예측(predict method에 feature test data입력해 예측 수행)
pred=dt_clf.predict(X_test)

In [34]:
#예측결과를 기반으로 예측성능 평가
from sklearn.metrics import accuracy_score
print('예측 정확도 : {0}'.format(accuracy_score(y_test,pred)))

예측 정확도 : 0.9333333333333333


In [35]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [40]:
print('feature names의 type:',type(iris.feature_names))
print('feature names의 shape:',len(iris.feature_names))
print(iris.feature_names)

print('target(label) name의 type:',type(iris.target_names))
print('target(label) name의 shape:',len(iris.target_names))
print(iris.target_names)

print('data의 type:',type(iris.data))
print('data의 shape:',iris.data.shape)
print(iris['data'])

print('target(label)의 type:',type(iris.target))
print('target(label)의 shape:',iris.target.shape)
print(iris.target)


feature names의 type: <class 'list'>
feature names의 shape: 4
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
target(label) name의 type: <class 'numpy.ndarray'>
target(label) name의 shape: 3
['setosa' 'versicolor' 'virginica']
data의 type: <class 'numpy.ndarray'>
data의 shape: (150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]


In [41]:
X_train,X_test,y_train,y_test=train_test_split(iris.data,iris.target,test_size=0.3,random_state=121)

In [42]:
dt_clf=DecisionTreeClassifier(random_state=121)

In [44]:
dt_clf.fit(X_train,y_train)

DecisionTreeClassifier(random_state=121)

In [45]:
pred=dt_clf.predict(X_test)

In [46]:
print('예측정확도 : {0}'.format(accuracy_score(y_test,pred)))

예측정확도 : 0.9555555555555556


In [47]:
from sklearn.model_selection import KFold

In [73]:
iris=load_iris()
features=iris.data
label=iris.target
dt_clf=DecisionTreeClassifier(random_state=156)

In [61]:
#5개의 폴드 세트로 분리하는 KFold객체와 폴드세트별 정확도를 담을 리스트객체 생성
kfold=KFold(n_splits=5)
cv_accuracy=[]
print('붓꽃 데이터 세트 크기:',features.shape[0])

붓꽃 데이터 세트 크기: 150


In [175]:
n_inter=0

# KFold객체는 split()을 호출하면 학습용/검증용 데이터로 분할할 수 있는 인덱스를 반환

for train_index,test_index in kfold.split(features):
    # Kfold.split()으로 반환된 인덱스를 이용해 학습용,검증용 테스트 데이터 추출
    X_train,X_test=features[train_index],features[test_index]
    y_train,y_test=label[train_index],label[test_index]
    
    #학습 및 예측
    dt_clf.fit(X_train,y_train)
    pred=dt_clf.predict(X_test)
    n_inter+=1
    
    #반복 시마다 정확도 측정
    accuracy=np.round(accuracy_score(y_test,pred),4)
    train_size=X_train.shape[0]
    test_size=X_test.shape[0]
    print('{0}교차 검증 정확도 : {1}, 학습데이터 크기 :{2}, 검증데이터 크기:{3}'.format(n_inter,accuracy,train_size,test_size))
    print('{0} 검증 세트 인덱스:{1}'.format(n_inter,test_index))
    
    cv_accuracy.append(accuracy)
    
print('\n평균 검증 정확도:',np.mean(cv_accuracy))

1교차 검증 정확도 : 1.0, 학습데이터 크기 :120, 검증데이터 크기:30
1 검증 세트 인덱스:[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
2교차 검증 정확도 : 0.9667, 학습데이터 크기 :120, 검증데이터 크기:30
2 검증 세트 인덱스:[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]
3교차 검증 정확도 : 0.8667, 학습데이터 크기 :120, 검증데이터 크기:30
3 검증 세트 인덱스:[60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]
4교차 검증 정확도 : 0.9333, 학습데이터 크기 :120, 검증데이터 크기:30
4 검증 세트 인덱스:[ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]
5교차 검증 정확도 : 0.7333, 학습데이터 크기 :120, 검증데이터 크기:30
5 검증 세트 인덱스:[120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]

평균 검증 정확도: 0.7022266666666668


In [143]:
n_inter=0

for test_index,train_index in kfold.split(features):
    X_train,X_test=features[train_index],features[test_index]
    y_train,y_test=label[train_index],label[test_index]
    
    dt_clf.fit(X_train,y_train)
    pred=dt_clf.predict(X_test)
    n_inter+=1
    
    accuracy=np.round(accuracy_score(y_test,pred),4)
    cv_accuracy.append(accuracy)
    
    
print(np.mean(cv_accuracy))    

0.6077677611940299


In [186]:
iris=load_iris()
iris_df=pd.DataFrame(iris.data,columns=iris.feature_names)
iris_df['label']=iris.target
iris_df['label'].value_counts()

2    50
1    50
0    50
Name: label, dtype: int64

In [188]:
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     label  
0        0  
1        0  
2        0  
3        0  
4        0  
..     ...  
145      2  
146      2  
147      2  
148      2  
149      2  

[150 rows x 5 columns]

In [193]:
kfold=KFold(n_splits=3)
n_iter=0
for train_index,test_index in kfold.split(iris_df):
    n_iter+=1
    label_train=iris_df['label'].iloc[train_index]
    label_test=iris_df['label'].iloc[test_index]
    
    
    print('##교차검증 :{0}'.format(n_iter))
    print('학습레이블 데이터 분포:\n',label_train.value_counts())
    print('검증레이블 데이터 분포:\n',label_test.value_counts())

##교차검증 :1
학습레이블 데이터 분포:
 2    50
1    50
Name: label, dtype: int64
검증레이블 데이터 분포:
 0    50
Name: label, dtype: int64
##교차검증 :2
학습레이블 데이터 분포:
 2    50
0    50
Name: label, dtype: int64
검증레이블 데이터 분포:
 1    50
Name: label, dtype: int64
##교차검증 :3
학습레이블 데이터 분포:
 1    50
0    50
Name: label, dtype: int64
검증레이블 데이터 분포:
 2    50
Name: label, dtype: int64


In [194]:
from sklearn.model_selection import StratifiedKFold

In [196]:
skf=StratifiedKFold(n_splits=3)

In [199]:
n_iter=0

for train_index, test_index in skf.split(iris_df,iris_df['label']):
    n_iter+=1
    label_train=iris_df['label'].iloc[train_index]
    label_test=iris_df['label'].iloc[test_index]
    
        
    print('##교차검증 :{0}'.format(n_iter))
    print('학습레이블 데이터 분포:\n',label_train.value_counts())
    print('검증레이블 데이터 분포:\n',label_test.value_counts())

##교차검증 :1
학습레이블 데이터 분포:
 2    34
1    33
0    33
Name: label, dtype: int64
검증레이블 데이터 분포:
 1    17
0    17
2    16
Name: label, dtype: int64
##교차검증 :2
학습레이블 데이터 분포:
 1    34
2    33
0    33
Name: label, dtype: int64
검증레이블 데이터 분포:
 2    17
0    17
1    16
Name: label, dtype: int64
##교차검증 :3
학습레이블 데이터 분포:
 0    34
2    33
1    33
Name: label, dtype: int64
검증레이블 데이터 분포:
 2    17
1    17
0    16
Name: label, dtype: int64


In [203]:
dt_clf=DecisionTreeClassifier(random_state=156)
skfold=StratifiedKFold(n_splits=3)
n_iter=0
cv_accuracy=[]
features=iris.data
label=iris.target

for train_index,test_index in skfold.split(features,label):
    X_train,X_test=features[train_index],features[test_index]
    y_train,y_test=label[train_index],label[test_index]
    
    dt_clf.fit(X_train,y_train)
    pred=dt_clf.predict(X_test)
    
    n_iter+=1
    accuracy=np.round(accuracy_score(y_test,pred),4)
    
    train_size=X_train.shape[0]
    test_size=X_test.shape[0]
    
    print('\n{0}교차 검증 정확도 : {1},학습데이터 크기:{2},검증데이터 크기:{3}'.format(n_iter,accuracy,train_size,test_size))
    print(train_index.shape,test_index.shape)
    
    cv_accuracy.append(accuracy)
    print('##교차 검증별 정확도:',np.round(cv_accuracy,4))
    print('##평균 검증별 정확도:',np.mean(cv_accuracy))


1교차 검증 정확도 : 0.98,학습데이터 크기:100,검증데이터 크기:50
(100,) (50,)
##교차 검증별 정확도: [0.98]
##평균 검증별 정확도: 0.98

2교차 검증 정확도 : 0.94,학습데이터 크기:100,검증데이터 크기:50
(100,) (50,)
##교차 검증별 정확도: [0.98 0.94]
##평균 검증별 정확도: 0.96

3교차 검증 정확도 : 0.98,학습데이터 크기:100,검증데이터 크기:50
(100,) (50,)
##교차 검증별 정확도: [0.98 0.94 0.98]
##평균 검증별 정확도: 0.9666666666666667


In [206]:
from sklearn.model_selection import cross_val_score,cross_validate
iris=load_iris()

In [208]:
features=iris.data
label=iris.target
dt_clf=DecisionTreeClassifier(random_state=156)

In [209]:
scores=cross_val_score(dt_clf,features,label,scoring='accuracy',cv=3)
print('교차 검증별 정확도:',np.round(scores,4))
print('평균 검증 정확도:',np.round(np.mean(scores),4))

교차 검증별 정확도: [0.98 0.94 0.98]
평균 검증 정확도: 0.9667


In [211]:
grid_parameters={'max_depth':[1,2,3],
                'min_samples_split':[2,3]}
grid_parameters

{'max_depth': [1, 2, 3], 'min_samples_split': [2, 3]}

In [227]:
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     label  
0        0  
1        0  
2        0  
3        0  
4        0  
..     ...  
145      2  
146      2  
147      2  
148      2  
149      2  

[150 rows x 5 columns]

In [213]:
from sklearn.datasets import load_iris
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier

iris = load_iris()
features=iris.data
label=iris.target

In [219]:
#데이터를 로딩하고 학습데이터와 테스트데이터 분리
X_train,X_test,y_train,y_test=train_test_split(features,label,random_state=121,test_size=0.2)

dt_clf=DecisionTreeClassifier()

#파라미터를 딕셔너리 형태로 설정
param_grid={'max_depth':[1,2,3],'min_samples_split':[2,3]}

#param_grid의 하이퍼파라미터를 3개의 train,test set 폴더로 나누어 테스트 수행설정
grid_tree=GridSearchCV(dt_clf,param_grid=param_grid,cv=3,refit=True)

#iris학습 데이터로 param_grid의 하이퍼 파라미터를 순차적으로 학습/평가
#GridSearchCV 객체의 fit()을 수행하면 최고성능을 나타낸 하이퍼파라미터 값과 그때의 평가 결과값이 best_params_,best_score_기록
grid_tree.fit(X_train,y_train)

#GridsearchCV 결과를 추출해 DataFrame 으로 변환
scores_df=pd.DataFrame(grid_tree.cv_results_)
scores_df[['params','mean_test_score','rank_test_score','split0_test_score','split1_test_score','split2_test_score']]

params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.700000                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.700000                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                3   
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                3   
4  {'max_depth': 3, 'min_samples_split': 2}         0.975000                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.975000                1   

   split0_test_score  split1_test_score  split2_test_score  
0              0.700                0.7               0.70  
1              0.700                0.7               0.70  
2              0.925                1.0               0.95  
3              0.925                1.0               0.95  
4              0.975                1.0               0.95  
5              0.975                1.0               0.95

In [223]:
#GridSearchCV의 refit으로 이미 학습된 estimator반환
estimator=grid_tree.best_estimator_
print(estimator)
print(grid_tree.best_params_)
print(grid_tree.best_score_)
#GridSearchCV의 best_estimator_는 이미 최적 학습이 되었으므로 별도 학습이 필요없음
pred=estimator.predict(X_test)
print('테스트 데이터 세트 정확도:{0}'.format(accuracy_score(y_test,pred)))

DecisionTreeClassifier(max_depth=3)
{'max_depth': 3, 'min_samples_split': 2}
0.975
테스트 데이터 세트 정확도:0.9666666666666667


In [226]:
pred1=grid_tree.predict(X_test)
accuracy_score(y_test,pred1)

0.9666666666666667

In [229]:
from sklearn.preprocessing import LabelEncoder

#LabelEncoder를 객체로 생성한 후 fit(),transform()을 호출해 레이블 인코딩을 수행
items=['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']
encoder=LabelEncoder()
encoder.fit(items)
encoder.transform(items)

array([0, 1, 4, 5, 3, 3, 2, 2], dtype=int64)

In [230]:
encoder.classes_

array(['TV', '냉장고', '믹서', '선풍기', '전자레인지', '컴퓨터'], dtype='<U5')

In [231]:
encoder.inverse_transform([4,5,2,0,1,1,3,3,])

array(['전자레인지', '컴퓨터', '믹서', 'TV', '냉장고', '냉장고', '선풍기', '선풍기'],
      dtype='<U5')

In [232]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

In [233]:
items=['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']

In [241]:
encoder=LabelEncoder()
encoder.fit(items)
labels=encoder.transform(items)

#2차원 데이터로 변환
labels=labels.reshape(-1,1)

#원핫 인코딩 적용
oh_encoder=OneHotEncoder()
oh_encoder.fit(labels)
oh_labels=oh_encoder.transform(labels)

print('원핫인코딩 데이터:',oh_labels.toarray())
print('원핫인코딩 데이터 차원:',oh_labels.shape)

원핫인코딩 데이터: [[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원핫인코딩 데이터 차원: (8, 6)


In [244]:
#get_dummies(): 사이킷런의 OnoHotEncoder와 다르게 문자열 카테고리 값을 숫자형으로 변환할 필요 없이 바로 변환 가능

import pandas as pd
df=pd.DataFrame({'item':['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']})
pd.get_dummies(df)

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자레인지  item_컴퓨터
0        1         0        0         0           0         0
1        0         1        0         0           0         0
2        0         0        0         0           1         0
3        0         0        0         0           0         1
4        0         0        0         1           0         0
5        0         0        0         1           0         0
6        0         0        1         0           0         0
7        0         0        1         0           0         0

In [250]:
iris=load_iris()
iris_df=pd.DataFrame(iris.data,columns=iris.feature_names)
print(iris_df.mean())
print(iris_df.var())

sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [252]:
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()
scaler.fit(iris_df)
iris_scaled=scaler.transform(iris_df)

In [255]:
iris_df_scaled=pd.DataFrame(iris_scaled,columns=iris.feature_names)
iris_df_scaled.mean()

sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

In [258]:
from sklearn.preprocessing import MinMaxScaler

scaler=MinMaxScaler()
scaler.fit(iris_df)
iris_scaled=scaler.transform(iris_df)

iris_df_scaled=pd.DataFrame(iris_scaled,columns=iris.feature_names)
print(iris_df_scaled.min())
print(iris_df_scaled.max())

sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64
